=== trongtindev/wutheringwaves-app/public/schema/character.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "voiceActors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "locale": { "type": "string", "enum": ["en", "jp", "zh", "ko"] }
        }
      }
    },
    "birthday": { "type": "string" },
    "birthplace": { "type": "string" },
    "quote": { "type": "string" },
    "quoteLocalized": { "type": "object" },
    "description": { "type": "string" },
    "descriptionLocalized": { "type": "object" },
    "stats": {
      "type": "object",
      "properties": {
        "atk": { "type": "number" },
        "def": { "type": "number" },
        "hp": { "type": "number" },
        "energy": { "type": "number" }
      },
      "required": ["atk", "def", "hp", "energy"]
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slug": { "type": "string" },
          "type": {
            "type": "string",
            "enum": [
              "Basic Attack",
              "Resonance Skill",
              "Resonance Liberation",
              "Inherent Skill",
              "Intro Skill",
              "Outro Skill",
              "Forte Circuit"
            ]
          },
          "name": { "type": "string" },
          "nameLocalized": { "type": "object" },
          "description": { "type": "string" },
          "descriptionLocalized": { "type": "object" },
          "params": { "type": "array", "items": { "type": "string" } }
        },
        "required": ["slug", "type", "name", "description"]
      }
    },
    "ascensions": {
      "type": "array",
      "items": {
        "properties": {
          "cost": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "item": {
                  "type": "string",
                  "$ref": "./item.components.json#/components/schemas/slug"
                },
                "quantity": { "type": "integer" }
              },
              "required": ["item", "quantity"]
            }
          },
          "minLevel": { "type": "integer" }
        },
        "required": ["cost", "minLevel"]
      }
    },
    "bestWeapons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "$ref": "./weapon.components.json#/components/schemas/slug"
          },
          "rank": { "type": "integer" },
          "different": { "type": "number" }
        },
        "required": ["item", "rank", "different"]
      }
    },
    "bestEchoSets": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "string",
              "$ref": "./echo.components.json#/components/schemas/sonataEffect"
            },
            "minItems": 1,
            "maxItems": 2
          },
          "different": { "type": "number" }
        },
        "required": ["items", "different"]
      },
      "minItems": 1
    },
    "bestMainEchoes": {
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "./echo.components.json#/components/schemas/slug"
      }
    },
    "bestEchoStats": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "type": "string", "enum": ["4-3-3-1-1", "4-4-1-1-1"] },
          "name": { "type": "string" },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "cost": { "type": "integer", "maximum": 4, "minimum": 1 },
                "stats": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "$ref": "./echo.components.json#/components/schemas/echoMainStat"
                  }
                }
              },
              "required": ["cost", "stats"]
            },
            "minItems": 1,
            "maxItems": 5
          }
        }
      },
      "minItems": 1
    },
    "skillPriority": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Basic Attack",
          "Resonance Skill",
          "Resonance Liberation",
          "Inherent Skill",
          "Intro Skill",
          "Outro Skill",
          "Forte Circuit"
        ]
      }
    },
    "bestTeams": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "role": {
                  "type": "string",
                  "$ref": "./character.components.json#/components/schemas/role"
                },
                "items": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "$ref": "./character.components.json#/components/schemas/slug"
                  },
                  "minItems": 1
                }
              },
              "required": ["role", "items"]
            }
          }
        },
        "required": ["items"]
      },
      "minItems": 1
    },
    "splashArt": { "anyOf": [{ "type": "boolean" }, { "type": "string" }] },
    "resonanceChain": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slug": { "type": "string" },
          "name": { "type": "string" },
          "nameLocalized": { "type": "object" },
          "params": { "type": "array", "items": { "type": "string" } },
          "description": { "type": "string" },
          "descriptionLocalized": { "type": "object" }
        }
      }
    }
  },
  "type": "object"
}

=== trongtindev/wutheringwaves-app/resources/characters/zhezhi.json
{
  "$schema": "../../public/schema/character.schema.json",
  "ascensions": [
    {
      "cost": [
        { "item": "shell-credit", "quantity": 5000 },
        { "item": "lf-howler-core", "quantity": 4 }
      ],
      "minLevel": 20
    },
    {
      "cost": [
        { "item": "shell-credit", "quantity": 10000 },
        { "item": "mf-howler-core", "quantity": 4 },
        { "item": "sound-keeping-tacet-core", "quantity": 3 },
        { "item": "lanternberry", "quantity": 4 }
      ],
      "minLevel": 40
    },
    {
      "cost": [
        { "item": "shell-credit", "quantity": 15000 },
        { "item": "mf-howler-core", "quantity": 8 },
        { "item": "sound-keeping-tacet-core", "quantity": 6 },
        { "item": "lanternberry", "quantity": 8 }
      ],
      "minLevel": 50
    },
    {
      "cost": [
        { "item": "shell-credit", "quantity": 20000 },
        { "item": "hf-howler-core", "quantity": 4 },
        { "item": "sound-keeping-tacet-core", "quantity": 9 },
        { "item": "lanternberry", "quantity": 12 }
      ],
      "minLevel": 60
    },
    {
      "cost": [
        { "item": "shell-credit", "quantity": 40000 },
        { "item": "hf-howler-core", "quantity": 8 },
        { "item": "sound-keeping-tacet-core", "quantity": 12 },
        { "item": "lanternberry", "quantity": 16 }
      ],
      "minLevel": 70
    },
    {
      "cost": [
        { "item": "shell-credit", "quantity": 80000 },
        { "item": "ff-howler-core", "quantity": 4 },
        { "item": "sound-keeping-tacet-core", "quantity": 16 },
        { "item": "lanternberry", "quantity": 20 }
      ],
      "minLevel": 80
    }
  ],
  "bestWeapons": [
    { "item": "rime-draped-sprouts", "rank": 1, "different": 100 }
  ],
  "description": "Zhezhi is a commissioned painter, quiet and shy with a dedication to her craft. She's not very eloquent, but her persistence and love for painting speak volumes.",
  "descriptionLocalized": {
    "vi": "Zhezhi là một họa sĩ được ủy thác, im lặng và nhút nhát với sự cống hiến cho đồ nghề của mình. Cô ấy không hùng biện lắm, nhưng sự kiên trì và yêu thích hội họa của cô ấy đã nói lên nhiều."
  },
  "quote": "What I wanted to say is, the sunlight on you right now is so beautiful. Can I ... paint you?",
  "quoteLocalized": {
    "vi": "Điều tôi muốn nói là, ánh nắng trên bạn lúc này thật đẹp. Tôi có thể... vẽ bạn chứ?"
  },
  "resonanceChain": [
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["15", "10", "27"],
      "description": "When casting Resonance Skill Creation's Zenith, Resonance Energy is restored by {0} and Crit. Rate is increased by {1}% for {2}s."
    },
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["6"],
      "description": "Max Inklit Spirits summoned by Resonance Liberation Living Canvas increases by {0}."
    },
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["15", "3", "27"],
      "description": "When Resonance Skill Manifestation, Resonance Skill Stroke of Genius, or Resonance Skill Creation's Zenith is cast, ATK increases by {0}%, stacking up to {1} time(s) for {2}s."
    },
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["20", "30"],
      "description": "When Resonance Liberation Living Canvas is cast, ATK of Resonators on the team increases by {0}% for {1}s."
    },
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["3", "1", "140"],
      "description": "For every {0} Inklit Spirits summoned by Resonance Liberation Living Canvas, {1} extra Inklit Spirit is summoned to perform a Coordinated Attack, dealing DMG equal to {2}% of Inklit Spirit's DMG, considered as Basic Attack DMG. This damage dealt will not further summon Inklit Spirit."
    },
    {
      "slug": "complex-simplicity",
      "name": "Complex Simplicity",
      "params": ["120"],
      "description": "When Resonance Skill Stroke of Genius or Resonance Skill Creation's Zenith is cast, an extra Ivory Herald will be summoned to deal DMG equal to {0}% of Resonance Skill Stroke of Genius's DMG, considered as Basic Attack DMG."
    }
  ],
  "skills": [
    {
      "slug": "dimming-brush",
      "name": "Dimming Brush",
      "type": "Basic Attack",
      "description": "**Basic Attack**\nPerform up to 3 consecutive strikes, dealing Glacio DMG**.\n\n**Heavy Attack**\nConsume STA to perform an attack, dealing Glacio DMG**.\n\n**Mid-air Attack**\nConsume STA to perform up to 2 consecutive attacks while in mid-air, dealing Glacio DMG**.\n\nDodge Counter\nUse Basic Attack after a successful Dodge to counterattack, dealing Glacio DMG**."
    },
    {
      "slug": "depiction",
      "name": "Depiction",
      "type": "Resonance Skill",
      "description": "**Press**\nDeal Glacio DMG**. If \"Afflatus\" is higher than 60, additionally consume 60 \"Afflatus\" to summon Spiritual Sketch: Left and Spiritual Sketch: Right on the ground.\n\n**Hold**\nDeal Glacio DMG**. If \"Afflatus\" is higher than 60, additionally consume 60 \"Afflatus\" to summon Spiritual Sketch: Left and Spiritual Sketch: Right in the air.\n\n**Press while in Mid-air**\nDeal Glacio DMG**. If \"Afflatus\" is higher than 60, additionally consume 60 \"Afflatus\" to summon Spiritual Sketch: Left and Spiritual Sketch: Right in the air."
    },
    {
      "slug": "spiritful-animation",
      "name": "Spiritful Animation",
      "type": "Resonance Liberation",
      "description": "Summon Inklit Spirit for assistance.\n\n**Inklit Spirit**\nWhen the active Resonator on the team deals DMG, Inklit Spirit will be summoned to perform a Coordinated Attack, dealing Glacio DMG, considered as Basic Attack DMG.\n\n- Each time DMG is dealt, 3 Inklit Spirit(s) will be summoned. Up to 21 Inklit Spirits can be summoned. Up to 1 Inklit Spirit(s) can be summoned every second.\n- The effect lasts for 30s or until max Inklit Spirits are summoned."
    },
    {
      "slug": "ink-and-wash",
      "name": "Ink and Wash",
      "type": "Forte Circuit",
      "description": "**Spiritual Sketch**\nUp to 1 of each of Spiritual Sketch: Left, Spiritual Sketch: Middle, and Spiritual Sketch: Right can exist at the same time, each lasting for 15s.\n\n**Heavy Attack**\nComposition When performing the 3 moves below, if \"Afflatus\" is higher than 30, consume STA and 30 \"Afflatus\" to attack the target, dealing Glacio DMG**, and summon Spiritual Sketch: Middle.\n\n - Hold the Basic Attack button shortly after Basic Attack Stage 3;\n- Press the Basic Attack button shortly after casting Resonance Skill; or\n- Hold the Basic Attack button while in mid-air.\n\n**Resonance Skill: Stroke of Genius**\nWhen a Spiritual Sketch is nearby, the Resonance Skill is replaced with Stroke of Genius. When it is cast, Zhezhi will: \n- Blink to the location of the Spiritual Sketch and remove it, then summon a crane spirit to attack the target, dealing Glacio DMG**, considered as Basic Attack DMG.\n- Gain 1 stack of \"Painter's Delight\", lasting for 8s and stacking up to 2 times.\n\nResonance Skill: Stroke of Maestro\n\nWhen a Spiritual Sketch is nearby and there are 2 stacks of \"Painter's Delight\", the Resonance Skill is replaced with Stroke of Maestro. When it is cast, Zhezhi will:\n- Blink to the location of the Spiritual Sketch and remove it, then summon a crane spirit to attack the target, dealing greater Glacio DMG**, considered as Basic Attack DMG, and additionally increasing the Basic Attack DMG Multiplier by 18% for 22s.\n\n\"Afflatus\"\nZhezhi can hold up to 90 \"Afflatus\". \nNormal Attacks grant \"Afflatus\".\nIntro Skill grants \"Afflatus\"."
    }
  ],
  "stats": { "atk": 30, "def": 90, "hp": 980, "energy": 100 },
  "voiceActors": [
    { "locale": "en", "name": "Shin-Fei Chen" },
    { "locale": "jp", "name": "Makino Yui" },
    { "locale": "zh", "name": "Miao Zi" },
    { "locale": "ko", "name": "Kim Ha Ru" }
  ]
}

=== trongtindev/wutheringwaves-app/resources/characters/youhu.json
{
  "$schema": "../../public/schema/character.schema.json",
  "description": "Youhu, a natural expert in identifying antiques, is a capable speaker with distinctive tastes.\n\nWhen dealing with treasures and antiques, this jubilant dynamo settles into calm perception, tracing their distant past through their wrinkles and textures.",
  "descriptionLocalized": {
    "vi": "Youhu có năng khiếu thẩm định bảo vật bẩm sinh, có tài hùng biện và sở hữu khiếu thẩm mỹ khác biệt.\n\nKhi đối mặt với những món cổ vật quý hiếm, cô ấy - người vốn hoạt bát và khác thường, sẽ bình tĩnh nhận định chúng một cách cẩn thận, như thể đang muốn thông qua các vân cùng kết cấu của chúng để truy tìm quá khứ xa xôi nào đó vậy."
  },
  "quote": "Here you go, a special edition of my poetry collection, hand-signed by moi! You are welcome!",
  "quoteLocalized": {
    "vi": "Đây là tập thơ đặc biệt có chữ ký của ta, tặng cho cậu đấy!"
  }
}

=== trongtindev/wutheringwaves-app/resources/characters/xiangli-yao.json
{
  "$schema": "../../public/schema/character.schema.json",
  "description": "Xiangli Yao is the Chief Researcher of Huaxu Academy at Jinzhou.",
  "descriptionLocalized": {
    "vi": "Điều tra viên Hiệu trưởng Học viện Huaxu, Xiangli Yao, thể hiện chuyên môn đặc biệt trong nhiều lĩnh vực nghiên cứu khác nhau mặc dù ông còn trẻ.\n\nAnh ấy là một tâm hồn nhẹ nhàng nhưng lý trí, nắm bắt những hiểu biết độc đáo và cam kết đối với nghiên cứu của Automata Mechanics."
  },
  "quote": "As truthseekers, we gauge the universe from within a nutshell. I'd love to hear your insights.",
  "quoteLocalized": {
    "vi": "Là những người tìm kiếm sự thật, chúng ta đánh giá vũ trụ từ trong một cái tóm tắt. Tôi muốn nghe những hiểu biết của bạn."
  },
  "resonanceChain": [
    {
      "slug": "prodigy-of-groteges",
      "name": "Prodigy of Protégés",
      "params": ["8"],
      "description": "When casting Resonance Skill Law of Reigns, deal 6 extra times of DMG, each equal to {0}% of that of Resonance Skill Law of Reigns."
    },
    {
      "slug": "traces-of-predecessors",
      "name": "Traces of Predecessors",
      "params": ["30", "8"],
      "description": "When **Resonance Skill** or **Resonance Liberation** Cogitation Model is cast, Crit. DMG is increased by {0}% for {1}s."
    },
    {
      "slug": "ruins-of-ancient",
      "name": "Ruins of Ancient",
      "params": ["24", "63"],
      "description": "After **Resonance Liberation** Cogitation Model is cast, the subsequent 5 Resonance Skills cast within {0}s are empowered to deal {1}% extra DMG."
    },
    {
      "slug": "vessel-of-rebirth",
      "name": "Vessel of Rebirth",
      "params": ["25", "30"],
      "description": "When casting **Resonance Liberation** Cogitation Model, all team members' **Resonance Liberation** gains {0}% DMG Bonus for {1}s."
    },
    {
      "slug": "end-of-stars",
      "name": "End of Stars",
      "params": ["222.09", "120"],
      "description": "The DMG Multiplier of **Outro Skill** Chain Rule is increased by {0}%. The DMG Multiplier of Resonance Liberation Cogitation Model is increased by {1}%."
    },
    {
      "slug": "solace-of-the-ordinary",
      "name": "Solace of the Ordinary",
      "params": ["76"],
      "description": "The Hypercubes obtained from **Resonance Liberation** Cogitation Model are enhanced, increasing the DMG Multiplier of **Resonance Skill** Law of Reigns by {0}%."
    }
  ],
  "skills": [
    {
      "slug": "probe",
      "type": "Basic Attack",
      "name": "Probe",
      "description": "**Basic Attack**\nPerform up to 5 consecutive attacks, dealing Electro DMG.\n\n**Heavy Attack**\nPerform a charged attack at the cost of STA, dealing Electro DMG.\n\n**Mid-air Attack**\nPerform a Plunging Attack from mid-air at the cost of STA, dealing Electro DMG.\n\n**Dodge Counter**\nUse Basic Attack after a successful Dodge to attack the target, dealing Electro DMG."
    },
    {
      "slug": "deduction",
      "type": "Resonance Skill",
      "name": "Deduction",
      "description": "Attack the target, dealing Electro DMG."
    },
    {
      "slug": "cogitation-model",
      "type": "Resonance Liberation",
      "name": "Cogitation Model",
      "description": "Attack the target, dealing Electro DMG. Enter **Intuition**. When in Intuition:\nObtain 3 Hypercube(s). Each time Resonance Skill **Law of Reigns** is cast, consume 1 Hypercube(s). Intuition ends once all Hypercubes are consumed.\nBasic Attack and Heavy Attack are replaced with Basic Attack Pivot - Impale, which performs up to 3 consecutive attacks, dealing Electro DMG.\nResonance Skill Deduction is replaced with Resonance Skill Divergence, which deals Electro DMG.\n**Dodge Counter** is replaced with **Dodge Counter Unfathomed**, considered as **Resonance Liberation DMG**."
    },
    {
      "slug": "forever-seeking",
      "type": "Forte Circuit",
      "name": "Forever Seeking",
      "description": "**Resonance Skill - Decipher**\n\nWhen Capacity reaches 100, Resonance Skill Deduction is replaced with Resonance Skill Decipher.\nConsume 100 Capacity to cast Resonance Skill Decipher, dealing Electro DMG, considered as Resonance Liberation DMG.\n\n**Resonance Skill - Law of Reigns**\nWhen in Intuition triggered by Resonance Liberation and Performance Capacity reaches 5, Resonance Skill Divergence is replaced with Resonance Skill Law of Reigns.\nConsume 5 Performance Capacity to cast Resonance Skill Law of Reigns, dealing Electro DMG, considered as Resonance Liberation DMG.\n\n**Mid-air Attack - Revamp**\nShortly after casting Resonance Skill Decipher or Resonance Skill Divergence, use Basic Attack to perform Mid-air Attack Revamp at the cost of STA, dealing Electro DMG, considered as Resonance Liberation DMG.\n\n**Capacity**\nXiangli Yao can hold up to 100 Capacity.\nEvery Normal Attack Probe on hit grants Capacity.\nEvery Resonance Skill Deduction on hit grants Capacity.\n\n**Performance Capacity**\nXiangli Yao can hold up to 5 Performance Capacity.\nWhen in Intuition triggered by Resonance Liberation:\nObtain 1 Performance Capacity when Stage 1 of Basic Attack Pivot - Impale hits a target.\nObtain 2 Performance Capacity when Stage 2 or 3 of Basic Attack Pivot - Impale hits a target.\nObtain 2 Performance Capacity for every Resonance Skill Divergence on hit.\nObtain 3 Performance Capacity for every Mid-air Attack Revamp on hit.\nObtain 2 Performance Capacity for every Dodge Counter Unfathomed on hit."
    },
    {
      "slug": "principle",
      "type": "Intro Skill",
      "name": "Principle",
      "description": "Attack the target, dealing Electro DMG."
    },
    {
      "slug": "chain-Rule",
      "type": "Outro Skill",
      "name": "Chain Rule",
      "params": ["237.63", "8", "2", "3"],
      "description": "When the **incoming Resonator's Basic Attack** hits a target, Xiangli Yao will attack the same target, dealing Electro DMG equal to {0}% of Xiangli Yao's ATK. This effect lasts for {1}s and can be triggered once every {2}s, up to {3} times."
    },
    {
      "slug": "knowing",
      "type": "Inherent Skill",
      "name": "Knowing",
      "params": ["5"],
      "description": "Gain {0}% Electro DMG Bonus."
    },
    {
      "slug": "focus",
      "type": "Inherent Skill",
      "name": "Focus",
      "description": "When in Intuition triggered by **Resonance Liberation**, Xiangli Yao's resistance to interruption is enhanced."
    }
  ],
  "stats": { "hp": 10625, "atk": 425, "def": 1222, "energy": 125 },
  "voiceActors": [
    { "locale": "en", "name": "Shaun Mendum" },
    { "locale": "jp", "name": "Kobayashi Chiaki" },
    { "locale": "zh", "name": "Ban Ma" },
    { "locale": "ko", "name": "Jung Eui Jin" }
  ]
}
